dns/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views
from main import views as main_views

# tastypie
from tastypie.api import Api
from dns.api import ZoneResource, RecordResource, ViewResource, ServerGroupResource, ServerResource, ServerConfigResource, RecordHistoryResource

v1_api = Api(api_name='v1')
v1_api.register(ServerGroupResource())
v1_api.register(ServerConfigResource())
v1_api.register(ServerResource())
v1_api.register(ViewResource())
v1_api.register(ZoneResource())
v1_api.register(RecordResource())
v1_api.register(RecordHistoryResource())

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', main_views.index, name='index'),
    url(r'^main/', include('main.urls', namespace='main')),
]

main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^zones/$', views.index, name='index'),
    url(r'^zone/(?P<zone_id>.+)/$', views.records, name='records'),
    url(r'^record/search/$', views.recordSearch, name='recordSearch'),
    url(r'^record/history/$', views.recordHistory, name='recordHistory'),
    url(r'^configs/$', views.configs, name='configs'),
    url(r'^config/(?P<config_id>[0-9]+)/$', views.configDetail, name='configDetail'),
    url(r'^config/generate/$', views.configGenerate, name='configGenerate'),
    url(r'^health/$', views.health, name='health'),
    url(r'^health/run/$', views.healthRun, name='healthRun'),
    url(r'^noauth/$', views.noauth, name='noauth'),
]

main/models.py
from django.db import models
from datetime import datetime
from simple_history.models import HistoricalRecords

record_type_choices = (
    (1, 'A'),
    (2, 'AAAA'),
    (3, 'MX'),
    (4, 'NS'),
    (5, 'TXT'),
    (6, 'SRV'),
    (7, 'CNAME'),
    (8, 'SPF'),
    (9, 'PTR'),
)

zone_type_choices = (
    (1, 'master'),
    (2, 'slave'),
    (3, 'forward')
)

config_type_choices = (
    (1, 'local'),
    (2, 'remote')
)

# Create your models here.
class View(models.Model):

    view = models.CharField(max_length=250, unique=True)
    comment = models.CharField(max_length=250)
    history = HistoricalRecords()

    def __str__(self):
        return self.view

class Server(models.Model):

    server = models.CharField(max_length=250, unique=True)
    comment = models.CharField(max_length=250)
    history = HistoricalRecords()

    def __str__(self):
        return self.server

class Zone(models.Model):

    zone = models.CharField(max_length=250)
    view = models.ForeignKey(View)
    ttl = models.PositiveIntegerField(default=600)
    origin = models.CharField(max_length=250)
    mail_addr = models.CharField(max_length=250)
    serial = models.PositiveIntegerField(default=1)
    refresh = models.PositiveIntegerField(default=7200)
    retry = models.PositiveIntegerField(default=3600)
    expire = models.PositiveIntegerField(default=1209600)
    minimum = models.PositiveIntegerField(default=600)
    type =  models.PositiveIntegerField(choices=zone_type_choices)
    history = HistoricalRecords()

    def __str__(self):
        return self.zone

class Record(models.Model):

    zone = models.ForeignKey(Zone)
    host = models.CharField(max_length=250)
    record_type = models.PositiveIntegerField(choices=record_type_choices, default=1)
    answer = models.CharField(max_length=250)
    ttl = models.PositiveIntegerField(default=600)
    priority = models.PositiveIntegerField(default=0)
    history = HistoricalRecords()

    def __str__(self):
        return "%s.%s" % (self.host, self.zone)

class ServerGroup(models.Model):

    group = models.CharField(max_length=250, unique=True)
    servers = models.ManyToManyField(Server)
    history = HistoricalRecords()

    def __str__(self):
        return self.group

class ServerConfig(models.Model):

    group = models.ForeignKey(ServerGroup)
    config = models.TextField(default='')
    type = models.PositiveIntegerField(choices=config_type_choices, default=2)
    name = models.CharField(max_length=250, default="zones.conf")
    history = HistoricalRecords()

    def __str__(self):
        return "%s - %s" % (str(self.group), self.name)

class CheckType(models.Model):

    type = models.CharField(max_length=250, unique=True)
    comment = models.CharField(max_length=250, default='')

    def __str__(self):
        return self.type

class Check(models.Model):

    type = models.ForeignKey(CheckType)
    check = models.CharField(max_length=250)
    parameter = models.TextField(default='')

    def __str__(self):
        return self.check

dns/views.py
from django.shortcuts import render

main/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.contrib.auth.decorators import permission_required
from django.db.models import Q

from .models import View, Zone, Record, record_type_choices, ServerConfig, Check

from dns.config import config
from dns.dns_health_check import CheckHealthActions

import math

# Create your views here.
def index(request):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    return render(request, 'main/zones.html')

def records(request, zone_id):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    # get zone
    zone = get_object_or_404(Zone, pk=zone_id)

    # get views pk for this zone
    views_list = []
    zone_list = Zone.objects.filter(zone=zone.zone)
    for zone_v in zone_list:
         views_list.append(zone_v.view.pk)

    cloneViews = View.objects.exclude(pk__in=views_list)

    context = {
        'zone': zone,
        'zone_list': zone_list,
        'record_type_choices': record_type_choices,
        'default_ttl': config['dns']['default']['ttl'],
        'cloneViews': cloneViews,
    }

    return render(request, 'main/records.html', context)

def recordSearch(request):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    context = {}

    return render(request, 'main/recordSearch.html', context)

@permission_required('serverconfig.can_open', login_url='/main/noauth/')
def configs(request):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    configs = ServerConfig.objects.all()

    context = {
        'configs': configs,
    }

    return render(request, 'main/configs.html', context)

@permission_required('serverconfig.can_open', '/main/noauth/')
def configDetail(request, config_id):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    serverConfig = get_object_or_404(ServerConfig, pk=config_id)

    context = {
        'serverConfig': serverConfig,
    }

    return render(request, 'main/configDetail.html', context)

@permission_required('serverconfig.can_open', '/main/noauth/')
def configGenerate(request):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    zones = Zone.objects.all()
    context = {
        'zones': zones,
    }

    return render(request, 'main/configGenerate.html', context)

def health(request):

    checks = Check.objects.values()

    for check in checks:
        check['result'] = 0
        check['message'] = ''
    
        cha = CheckHealthActions(check)
        check = cha.run()
    
    context = {
        'checks': checks,
    }

    return render(request, 'main/health.html', context)


def healthRun(request):

    checks = Check.objects.values()

    health = 0
    for check in checks:
        check['result'] = 0
        check['message'] = ''
    
        cha = CheckHealthActions(check)
        check = cha.run()

        if check['result'] != 0:
            health = 1

    return HttpResponse(health)

def noauth(request):

    return render(request, 'main/not_authorized.html')

def recordHistory(request):

    if not request.user.is_authenticated():
        return render(request, 'main/not_authorized.html')

    context = {}

    return render(request, 'main/recordHistory.html', context)

main/templates/main/configDetail.html
{% extends "main/index.html" %}

{% block content %}
<div class="container">
<h3>{{ serverConfig.group }}</h3>
{% csrf_token %}
<form id="serverConfigForm">
    <textarea id="configArea" name="config" rows="20" style="min-width: 70%">
    {{ serverConfig.config }}
    </textarea>
    <script src="/mode/nginx.js"></script>
    <script>
    var editor = CodeMirror.fromTextArea(configArea, {
        lineNumbers: true
    });
    editor.setSize(1024,1024);
    </script>
    <br/>
    <span>
        <input type="button" class="btn btn-primary" value="Save" onClick="dns_patchConfig({{ serverConfig.id }});">
        &nbsp; &nbsp;
        <input type="button" class="btn btn-primary" value="Apply" onClick="dns_applyConfig({{ serverConfig.id }});">
    </span>
</form>
</div>
<br/>
{% endblock %}

main/templates/main/configGenerate.html
{% extends "main/index.html" %}

{% block content %}

<div class="container">
<h3>Master config</h3>
<pre>
view internal {

    match-clients { acl-internal; };
    allow-recursion { any; };
    allow-transfer { key internal-key; };
    allow-query { any; };

    {% for zone in zones %}
    {% if zone.get_type_display == 'slave' %}
    zone "{{ zone.zone }}" { type {{ zone.get_type_display }}; file "zones/{{ zone.view.view }}_{{ zone.zone }}"; masters { 10.25.10.137; }; };
    {% else %}
    zone "{{ zone.zone }}" { type {{ zone.get_type_display }}; file "zones/{{ zone.view.view }}_{{ zone.zone }}"; also-notify { {{ zone.view.view }}-notify; }; };
    {% endif %}
    {% endfor %}
};

view asia {

    match-clients { acl-asia; };
    allow-transfer { key asia-key; };
    allow-query { any; };


    {% for zone in zones %}
        {% if zone.view.view == 'external' %}
    zone "{{ zone.zone }}" { in-view internal; };
        {% elif zone.view.view == 'asia' %}
    zone "{{ zone.zone }}" { type master; file "zones/{{ zone.view.view }}_{{ zone.zone }}"; also-notify { {{ zone.view.view }}-notify; }; };
        {% endif %}
    {% endfor %}

};

view external {

    match-clients { any; };
    allow-transfer { key external-key; };
    allow-query { any; };

    {% for zone in zones %}
        {% if zone.view.view == 'external' %}
    zone "{{ zone.zone }}" { in-view internal; };
        {% endif %}
    {% endfor %}
};
</pre>
<h3>Slave config</h3>
<pre>
view internal {

    match-clients { acl-internal; };
    allow-recursion { any; };
    allow-query { any; };

    {% for zone in zones %}
    zone "{{ zone.zone }}" {
        {% if zone.get_type_display == 'master' %}
        type slave; file "zones/{{ zone.view.view }}_{{ zone.zone }}"; masters { {{ zone.view.view }}-master-servers; };
        {% else %}
        type forward; forwarders { 10.25.3.221; 10.25.10.123; };
        {% endif %}
    };
    {% endfor %}
};

view asia {

    match-clients { acl-asia; };
    allow-query { any; };


    {% for zone in zones %}
        {% if zone.view.view == 'external' %}
    zone "{{ zone.zone }}" { in-view internal; };
        {% elif zone.view.view == 'asia' %}
    zone "{{ zone.zone }}" { type slave; file "zones/{{ zone.view.view }}_{{ zone.zone }}"; masters { {{ zone.view.view }}-master-servers; }; };
        {% endif %}
    {% endfor %}

};

view external {

    match-clients { any; };
    allow-query { any; };

    {% for zone in zones %}
        {% if zone.view.view == 'external' %}
    zone "{{ zone.zone }}" { in-view internal; };
        {% endif %}
    {% endfor %}
};
</pre>
</div>

{% endblock %}

main/templates/main/configs.html
{% extends "main/index.html" %}

{% block content %}
<div class="container">
<table class="table" id="configTable">
<thead>
    <tr>
        <th>Name</th>
        <th>Filename</th>
        <th>Type</th>
        <th>Action</th>
    </tr>
</thead>
<tbody>

{% for config in configs %}
<tr>
    <td>{{ config.group }}</td>
    <td>{{ config.name }}</td>
    <td>{{ config.get_type_display }}</td>
    <td><a href="{% url 'main:configDetail' config.id %}">edit</a></td>
</tr>
{% endfor %}


</tbody>
</table>
</div>
{% endblock %}

main/templates/main/health.html
{% extends "main/index.html" %}

{% block content %}

<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th>Check</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
    {% for check in checks %}
        <tr>
            <td>{{ check.check }}</td>
            
            <td>
            {% if check.result == 0 %}
                <p class="text-success">OK</p>
            {% else %}
                <p class="text-warning">{{ check.message }}</p>
            {% endif %}
            </td>
        </tr>
    {% endfor %}

        </tbody>
    </table>

</div>
{% endblock %}

main/templates/main/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

{% block title %}
    <title>DNS Manager</title>
{% endblock %}

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/animate.css" %}" rel="stylesheet">
    <link href="{% static "css/codemirror.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
    <script src="{% static "js/jquery-1.12.1.min.js" %}"></script>
    <script src="{% static "js/jquery.cookie.js" %}"></script>
    <script src="{% static "js/jsrender.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/bootstrap-notify.min.js" %}"></script>
    <script src="{% static "js/codemirror.js" %}"></script>
    <script src="{% static "js/dns.js" %}"></script>

  </head>

  <body>

<nav id="custom-bootstrap-menu" class="navbar navbar-default" role="navigation">
<div class="container">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">
            DNS Manager
        </a>
        <button class="navbar-toggle collapsed" type="button"
data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse bs-navbar-collapse"
id="bs-navbar-collapse">
        <ul class="nav navbar-nav" id="nav">
            <li>
               <a href="{% url 'main:index' %}">Zones</a>
            </li>
        </ul>
        <ul class="nav navbar-nav" id="nav">
            <li class="dropdown">
                <a href="{% url 'main:recordSearch' %}">Records</a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'main:recordSearch' %}">Search</a>
                    </li>
                    <li>
                        <a href="{% url 'main:recordHistory' %}">History</a>
                    </li>
                </ul>
            </li>
        </ul>
        {% if perms.serverconfig.can_change %}
        <ul class="nav navbar-nav" id="nav">
            <li>
               <a href="{% url 'main:configs' %}">Configs</a>
            </li>
        </ul>
        <ul class="nav navbar-nav" id="nav">
            <li>
               <a href="{% url 'main:health' %}">Health</a>
            </li>
        </ul>
        {% endif %}
        <ul class="nav navbar-nav navbar-right">
            <li>
                {% if user.is_authenticated %}
                    <a><span class="glyphicon glyphicon-user">&nbsp;{{ user.get_username }}</span></a>
                {% endif %}
            </li>
        </ul>
    </div>

</div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

main/templates/main/not_authorized.html
{% extends "main/index.html" %}

{% block content %}
<div class="container">
    <h2>You are not authorized</h2>
</div>
{% endblock %}

main/templates/main/recordHistory.html
{% extends "main/index.html" %}

{% block content %}

<script id="RecordTemplate" type="text/x-jsredner">

    <tr id="record_<%> id %>">
        <td><%> record_type_text %></td>

        <%if host == '@'%>
            <td><span class="text-muted"><%> zone.zone %></span></td>
        <%else%>
            <td><%> host %>.<span class="text-muted"><%> zone.zone %></span></td>
        <%/if%>

        <td><%> zone.view.view %></td>
        <td><%> answer %></td>
        <td><%> ttl %></td>
        <%if record_type_text == 'MX'%>
            <td><%> priority %></td>
        <%else%>
            <td></td>
        <%/if%>
        <td>
            <%> history_date %></td>
        </td>
        <td>
            <%> history_user.username %>
        </td>
        <td>
            <%> history_type %>
        </td>
    </tr>

</script>


<div class="container">

<form class="form-horizontal">

<div class="form-group">
    <label class="control-label col-sm-1" for="hostFilter">Host</label>
    <div class="col-sm-3">
        <input type="text"  id="hostFilter" class="form-control filtercl">
    </div>
    <div class="col-sm-4">
        <label class="control-label"for="totalRecords">Records found: </label>
        <span id="totalRecords"></span>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-1" for="zoneFilter">Zone</label>
    <div class="col-sm-3">
        <input type="text" id="zoneFilter" class="form-control filtercl">
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-1" for="answerFilter">Answer</label>
    <div class="col-sm-3">
        <input type="text" id="answerFilter" class="form-control filtercl">
    </div>
</div>

</form>

<table class="table" id="recordTable" style="word-wrap: break-word; table-layout: fixed;">
<thead>
    <tr>
        <th class="col-md-1">type</th>
        <th class="col-md-2">host</th>
        <th class="col-md-1">view</th>
        <th class="col-md-2">answer</th>
        <th class="col-md-1">ttl</th>
        <th class="col-md-1">priority</th>
        <th class="col-md-2">date</th>
        <th class="col-md-2">user</th>
        <th class="col-md-1">action</th>
    </tr>
</thead>
<tbody id="recordList">

</tbody>
</table>
<button id="showMoreButton" class="hidden center-block btn btn-info" onClick="showMoreRecords();">Show more</button>
<br/>
</div>

<script type="text/javascript">
    var RecordSearch = {};
    RecordSearch.offset = 0;
    $( document ).ready( function() {
        dns_historyRecords();
    } );

    $( ".filtercl" ).keyup(function() {
        RecordSearch.offset = 0;
        $( '#recordList' ).empty();
        dns_historyRecords(RecordSearch.offset, 40, $('#hostFilter').val(), $('#zoneFilter').val(), $('#answerFilter').val());
    });

    function showMoreRecords() {

        RecordSearch.offset += 40;
        dns_historyRecords(RecordSearch.offset, 40, $('#hostFilter').val(), $('#zoneFilter').val(), $('#answerFilter').val());
    }

</script>
{% endblock %}

main/templates/main/records.html
{% extends "main/index.html" %}

{% block content %}

<script id="RecordTemplate" type="text/x-jsredner">

    <tr id="record_<%> id %>">
        <td><%> record_type_text %></td>

        <%if host == '@'%>
            <td>{{ zone.zone }}</td>
        <%else%>
            <td><%> host %>.{{ zone.zone }}</td>
        <%/if%>

        <td><%> answer %></td>
        <td><%> ttl %></td>
        <%if record_type_text == 'MX'%>
            <td><%> priority %></td>
        <%else%>
            <td></td>
        <%/if%>
        <td>

            <a href="javascript:void(0);" onClick="dns_editRecord(<%> id %>);">edit</a> | 
            <a href="javascript:void(0);" onMouseDown="dns_deleteRecordTimer(<%> id %>);">delete</a>
        </td>
    </tr>

</script>

<script id="addRecordTemplate" type="text/x-jsredner">

    <tr id="addRecordTr">
    <form id="addRecordForm">
    {% csrf_token %}
    <input type="hidden" value="/api/v1/zone/{{ zone.id }}/" name="zone" form="addRecordForm">
    <td>
        <select name="record_type" id="record_type" onChange="dns_priorityRecord();" form="addRecordForm">
        {% for value, text in record_type_choices %}
            <option value="{{ value }}">{{ text }}</option>
        {% endfor %}
        </select>
    </td>
    <td>
        <input type="text" name="host" id="host" form="addRecordForm">.{{ zone.zone }}</input>
    </td>
    <td>
        <input type="text" name="answer" id="answer" form="addRecordForm"></input>
    </td>
    <td class="col-sm-1">
        <input class="col-sm-10" type="text" name="ttl" id="ttl" value="{{ default_ttl }}" form="addRecordForm"></input>
    </td>
    <td class="col-sm-1" id='priorityTd'>
        <input type="hidden" name="priority" id="priority" value="0" form="addRecordForm"></input>
    </td>
    <td>
        <input type="button" class="btn btn-primary" value="Add" onClick="dns_addRecord();">
    </td>
    </form>
</tr>
</script>

<script id="priorityWithInput" type="text/x-jsredner">

    <input class="col-sm-10" type="text" name="priority" id="priority" form="addRecordForm"></input>

</script>

<script id="priorityWithoutInput" type="text/x-jsredner">

    <input type="hidden" name="priority" id="priority" value="0" form="addRecordForm"></input>

</script>

<script id="editRecordTemplate" type="text/x-jsredner">

    <form id="editRecordForm_<%> id %>"></form>

    <tr id="record_<%> id %>">
    {% csrf_token %}
    <input type="hidden" value="/api/v1/zone/{{ zone.id }}/" name="zone" form="editRecordForm_<%> id %>">
    <input type="hidden" value="<%> id %>" name="record_id" form="editRecordForm_<%> id %>">

    <td>
        <input type="hidden" name="record_type" value="<%> record_type %>" form="editRecordForm_<%> id %>">
        <%> record_type_text %>
    </td>

    <td>
        <%if host == '@'%>
            <input type="text" name="host" id="host" form="editRecordForm_<%> id %>">.{{ zone.zone }}</input>
        <%else%>
            <input type="text" name="host" id="host" form="editRecordForm_<%> id %>" value="<%> host %>">.{{ zone.zone }}</input>
        <%/if%>
    </td>

    <td>
        <input type="text" name="answer" id="answer" form="editRecordForm_<%> id %>" value="<%> answer %>"></input>
    </td>

    <td class="col-sm-1">
        <input class="col-sm-10" type="text" name="ttl" id="ttl" value="<%> ttl %>" form="editRecordForm_<%> id %>"></input>
    </td>

    <td class="col-sm-1">
        <%if record_type_text == 'MX'%>
        <input class="col-sm-10" type="text" name="priority" id="priority" value="<%> priority %>" form="editRecordForm_<%> id %>"></input>
        <%else%>
        <input type="hidden" name="priority" id="priority" value="0" form="editRecordForm_<%> id %>"></input>
        <%/if%>
    </td>

    <td>
        <input type="button" class="btn btn-warning" value="Update" onClick="dns_patchRecord(<%> id %>);"> | 
        <input type="button" class="btn btn-primary" value="Cancel" onClick="dns_patchCancel(<%> id %>);">
    </td>
</tr>
</script>

<script id="notifyGenerate" type="text/x-jsredner">
    <span class="glyphicon glyphicon-warning-sign"> <b>Change & generate reminder!</b></span>
    <p>This zone is also present in another view(s).<br/>
    Do not forget to change & generate it there as well.</p>
</script>

<div class="container">

<h3><span class="text-warning">{{ zone.zone }}</span> in view <span class="text-info">{{ zone.view.view }}</span></h3>

<div class="row">
    <div class="col-md-6">
        <h4>SOA</h4>
        <dl class="dl-horizontal">
            <dt>origin:</dt>
            <dd>{{ zone.origin }}</dd>
            <dt>mail_addr:</dt>
            <dd>{{ zone.mail_addr }}</dd>
            <dt>serial:</dt>
            <dd>{{ zone.serial }}</dd>
            <dt>refresh:</dt>
            <dd>{{ zone.refresh }}</dd>
            <dt>retry:</dt>
            <dd>{{ zone.retry }}</dd>
            <dt>expire:</dt>
            <dd>{{ zone.expire }}</dd>
            <dt>minimum:</dt>
            <dd>{{ zone.minimum }}</dd>
        </dl>
    </div>
    <div class="col-md-6">
    <h4>Commands</h4>
        <input type="button" class="btn btn-primary" value="Generate" onClick="dns_generateZone({{ zone.id }});"> <span class="text-muted">apply changes and generate new zone file</span>
        <br/><br/>
        <form id="cloneZoneForm"></form>
        <input type="button" class="btn btn-warning" value="Clone" onMouseDown="dns_cloneZoneTimer();"> zone to
        <input type="hidden" form="cloneZoneForm" value="{{ zone.id }}" name="zone_id"> 
        <select form="cloneZoneForm" name="view_id">
        {% for view in cloneViews %}
            <option value="{{ view.pk }}">{{ view.view }}</option>
        {% endfor %}
        </select>
        <span class="text-muted"> clones zone to view. Use with caution.</span>

        <br/><br/>
        {% if zone_list.count > 1 %}
            Other views:
            {% for zone_v in zone_list %}
                {% if zone_v.view.view != zone.view.view %}
                    <a href="{% url 'main:records' zone_v.id %}">{{ zone_v.view.view }}</a>
                {% endif%}
            {% endfor %}
        {% endif %}

    </div>
</div>
<h4>Records</h4>
<table class="table" id="recordTable" style="word-wrap: break-word; table-layout: fixed;">
<thead>
    <tr>
        <th class="col-md-1">type</th>
        <th class="col-md-3">host</th>
        <th class="col-md-3">answer</th>
        <th class="col-md-1">ttl</th>
        <th class="col-md-1">priority</th>
        <th class="col-md-3">actions</th>
    </tr>
</thead>
<tbody id="recordList">

</tbody>
</table>
</div>

<script type="text/javascript">
    $( document ).ready( function() {
        dns_getRecords({{ zone.id }});
    } );

    function dns_checkZoneView() {
        {% if zone_list.count > 1 %}
        $.notify({
           message: $( '#notifyGenerate' ).render(),
        },{
            type: 'warning',
            timer: 5000,
        });
        {% endif %}
        return;

    }

</script>
{% endblock %}

main/templates/main/zones.html
{% extends "main/index.html" %}

{% block content %}


<script id="zoneListTemplate" type="text/x-jsrender">

    <tr>
        <%if type == 'slave'%>
            <td><%>zone%></td>
        <%else%>
            <td><a href="/main/zone/<%>id%>"><%>zone%></a></td>
        <%/if%>
        <td><%>view.view%></td>
        <td><%>type%></td>
    </tr>

</script>

<div class="container">
<label for="zoneFilter">Filter by zone:</label>
<input type="text" id="zoneFilter" autofocus>
<table class="table" id="zonesTable">
<thead>
    <tr>
        <th>Zone</th>
        <th>View</th>
        <th>Type</th>
    </tr>
</thead>
<tbody id="zoneList">

</tbody>
</table>
</div>

<script type="text/javascript">
    $( document ).ready( function() {
        dns_getZones();
    } );

    $( '#zoneFilter' ).keypress(function() {
        dns_getZones($('#zoneFilter').val());
    });
</script>
{% endblock %}